### ISSUE TITLE
icon delete

### ISSUE THREAD

**Issue by tonho911** [NaiveInvestigator/mpv-config#1]
where do I delete this icon, sir?
because I accidentally clicked and lost the video on my HDD
![Screenshot at Jan 04 22-17-36](https://github.com/NaiveInvestigator/mpv-config/assets/148846306/808009f8-e7f5-4085-861d-8f446e200457)

**Comment by NaiveInvestigator** [comment]
Good idea i think i should make it the default.

> where do I delete this icon, sir?

To do that go to your `portable_config` folder. Enter the `script-opts` folder. Inside you should find a file named `uosc.conf`

Replace that file with the one below.

[uosc.txt](https://github.com/NaiveInvestigator/mpv-config/files/13838685/uosc.txt) (After downloading rename this file to uosc.conf btw)

Hope this helps!

Edit: Do let me know if it worked or not btw.

Edit 2: Also if you're using a Mac I would recommend you to use [IINA](https://iina.io/) instead. It is mpv but made to work with macos.

**Comment by tonho911** [comment]
> Good idea i think i should make it the default.
> 
> > where do I delete this icon, sir?
> 
> To do that go to your `portable_config` folder. Enter the `script-opts` folder. Inside you should find a file named `uosc.conf`
> 
> Replace that file with the one below.
> 
> [uosc.txt](https://github.com/NaiveInvestigator/mpv-config/files/13838685/uosc.txt) (After downloading rename this file to uosc.conf btw)
> 
> Hope this helps!
> 
> Edit: Do let me know if it worked or not btw.
> 
> Edit 2: Also if you're using a Mac I would recommend you to use [IINA](https://iina.io/) instead. It is mpv but made to work with macos.

Thank you for the instructions and now the delete icon is gone from sight.
I don't like Iina, I really don't like it...
1. The config is a little confusing
2. The main thing is that the color tone is inconsequential and requires settings here and there to get the color you want (saturation and others) and even if it suits your wishes, not all video configurations are the same, just try a few videos and feel the error
3. The only advantage is that there is a playlist
The best one in my opinion (according to my needs) is potplayer but unfortunately this is only available on Windows and even though it uses Wine, Crossover and others, it's still not as good as directly on Windows and the developer didn't make it for Mac.
I think there are many disadvantages to MPV, including that it is quite difficult to configure and it doesn't provide a playlist that is as easy as Potplayer, which just adds more or less according to the user's wishes, but the advantages are that the tone color is quite close to accurate in all videos and it is automatic.
If you know how to add playlists to MPV automatically, automatically save when the application is closed, and when the application is opened, everything in my playlist is there, please teach me
I've tried Google pages to look for it but nothing works, thank you bro

**Comment by NaiveInvestigator** [comment]
I see i never used IINA personally so i didnt know the issues. Atleast you tried that.

> If you know how to add playlists to MPV automatically, automatically save when the application is closed, and when the application is opened, everything in my playlist is there, please teach me
I've tried Google pages to look for it but nothing works, thank you bro

Hmm I quite didnt get what you mean. I think giving an example would help me.

To open playlists, just drag and drop them in the mpv window, or double-click the playlist. To save the playlists you can just press ALT + s (be careful that the CAPSLOCK is not on however).
